### ISSUE TITLE
Send Button Debouncing when Image Attached

### ISSUE THREAD

**Issue by Peyton-Spencer** [ditto-assistant/ditto-app#101]
User tapped send multiple times. Resulted in a stream of messages and too many requests.

**Comment by omarzanji** [comment]
This only happens for image attachments btw

**Comment by omarzanji** [comment]
Fixed as of 0.8.130 with new logic for greying out / disabling the send button while Ditto is typing. Although there is a new bug that happens when sub-sequent calls are made with Tools, the send button enables again while a script is generating, for example, when it should still be greyed out.
