### ISSUE TITLE
Convert User's Memory Collection to Firestore Vector Index

### ISSUE THREAD

**Issue by omarzanji** [ditto-assistant/ditto-app#110]
1. Use the existing `scripts\convert_memory_to_vector.py` to convert a test user's memory collection to use Firestore Vector fields for embeddings. Keep the old field "embedding" for front-ends that don't get the update. Create a new field "embedding_vector" for the converted field.
2. Create a simple min-instances=0 Cloud Run function that runs the command for a new user:

`gcloud firestore indexes composite create --project=PROJECT_NAME_HERE --collection-group=COLLECTION_HERE --query-scope=COLLECTION --field-config=vector-config='{"dimension":"768","flat": "{}"}',field-path=embedding_vector`

3. Add logic to the front-end to use the new vector field for long term memory vector searches.

**Comment by Peyton-Spencer** [comment]
Implemented in the js backend. Should be integrated in go backend.
