### ISSUE TITLE
Settings back button causes re-scroll of messages

### ISSUE THREAD

**Issue by Peyton-Spencer** [ditto-assistant/ditto-app#135]
https://github.com/user-attachments/assets/fc26e226-bd19-4d66-a2be-061cd78a1477

**Comment by Peyton-Spencer** [comment]
Issue still exists. New video
https://github.com/user-attachments/assets/4d041f6b-1011-4f8d-b588-158f03c16f80

**Comment by omarzanji** [comment]
Fixed as of 0.8.130, although we can still fix the random stutter on some clients.
