### ISSUE TITLE
OPENSCAD: generation finished, loading state stuck on message

### ISSUE THREAD

**Issue by Peyton-Spencer** [ditto-assistant/ditto-app#143]
![Screenshot_20241104-012647.png](https://github.com/user-attachments/assets/8265e03d-ecb9-4781-b11c-3e9e66a1c203)

**Comment by Peyton-Spencer** [comment]
I already got the file downloaded but even after closing and reopening the app I still have this loading state on the message.

**Comment by omarzanji** [comment]
Fixed as of v0.8.130
